apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-restricted-binding
  namespace: logging
subjects:
- kind: ServiceAccount
  name: your-service-account  # The service account to bind the role to
  namespace: logging
roleRef:
  kind: Role
  name: role-logging-ns
  apiGroup: rbac.authorization.k8s.io
