# helm -n logging install -f kibana-values.yaml kibana elastic/kibana
# kubectl get secrets --namespace=logging docker-desktop-cluster-master-credentials -ojsonpath='{.data.password}' | base64 -d
# kubectl delete -n logging po,deploy,job,configmap,secret,svc,serviceaccount,role,rolebinding --selector app=kibana

elasticsearchHosts: "https://docker-desktop-cluster-master:9200"
elasticsearchCertificateSecret: docker-desktop-cluster-master-certs
elasticsearchCertificateAuthoritiesFile: ca.crt
elasticsearchCredentialSecret: docker-desktop-cluster-master-credentials

replicas: 1
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.12.0"

service:
  type: ClusterIP
  port: 5601

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     ingress.kubernetes.io/ssl-redirect: "false"
#   hosts:
#     - host: kibana.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
